
import Head from 'next/head'
import Image from 'next/image'

import AppBody from '../components/app'
import { ContactsProvider } from 'context/contactsContext'

import WithAuth from 'utils/withAuth'

const Home = () => {

  return (<WithAuth>

    <div className='w-full h-screen bg-[whitesmoke] flex items-center justify-center'>
      <Head>
        <title>Apollo Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <ContactsProvider>
        <AppBody/>
      </ContactsProvider>


    </div>

  </WithAuth>)
}


export default Home
